specVersion: 0.2.0
name: moonbeam-orbiter
version: 0.0.1
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/subquery/moonbeam-alpha-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2255000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
